name = "training-record-app"
main = "functions/index.ts"
compatibility_date = "2024-01-01"

# Enable experimental features
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "training-record-app-dev"

[env.production]
name = "training-record-app-prod"

[[d1_databases]]
binding = "DB"
database_name = "training-app-db"
database_id = ""
migrations_dir = "migrations"

[vars]
ENVIRONMENT = "development"